FROM node:18-alpine3.16 as build-env

WORKDIR /app

RUN corepack enable
COPY ./end_user/. .
RUN --mount=type=cache,target=/root/.yarn YARN_CACHE_FOLDER=/root/.yarn yarn install
RUN --mount=type=cache,target=/root/.yarn YARN_CACHE_FOLDER=/root/.yarn yarn build

FROM nginx:1.23.2-alpine as run-env
COPY --from=build-env /app/dist/. /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
