FROM python:3.9.16-slim-bullseye

WORKDIR /app
COPY backend/. .
RUN --mount=type=cache,target=/root/.cache python3 -m pip install --upgrade pip setuptools wheel
RUN --mount=type=cache,target=/root/.cache python3 -m pip install -r requirements.txt
RUN python -m alembic upgrade head
RUN apt-get update && apt-get install -y tzdata libglib2.0-0 libgl1-mesa-glx && rm -rf /var/lib/apt/lists/*
ENV TZ=Asia/Jakarta

CMD [ "/bin/sh", "-c", "python -m alembic upgrade head && python app.py" ]