version: "3"
services:
  admin_frontend:
    image: weatherpred_admin_frontend
    restart: unless-stopped
    ports:
      - "7001:80"

  end_user:
    image: weatherpred_end_user_frontend
    restart: unless-stopped
    ports:
      - "7000:80"

  backend:
    image: weatherpred_backend
    restart: unless-stopped
    network_mode: "host"
    ports:
      - "7002:7002"
    volumes:
      - "./db/:/app/db/"
      - "./files/:/app/files/"

  scheduler:
    image: weatherpred_scheduler
    restart: unless-stopped
    environment:
      - "BACKEND_URL=http://localhost:7002"
      - "SCHEDULER_INTERVAL=300"
      - "PREDICT_DUMMY=yes"
