"""add cam lat lon

Revision ID: 07c8fed5e772
Revises: acb4251c29ab
Create Date: 2022-12-12 22:46:43.196671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c8fed5e772'
down_revision = 'acb4251c29ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('cameras', sa.Column('lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'lng')
    op.drop_column('cameras', 'lat')
    # ### end Alembic commands ###
