version: "3"
services:
  admin_frontend:
    image: weatherpred_admin_frontend
    restart: unless-stopped
    ports:
      - "#{admin_port}:80"

  end_user:
    image: weatherpred_end_user_frontend
    restart: unless-stopped
    ports:
      - "#{end_user_port}:80"

  backend:
    image: weatherpred_backend
    restart: unless-stopped
    ports:
      - "#{backend_port}:7002"
    volumes:
      - "./db/:/app/db/"
      - "./files/:/app/files/"

  scheduler:
    image: weatherpred_scheduler
    restart: unless-stopped
    environment:
      - "BACKEND_URL=#{base_url}"
      - "SCHEDULER_INTERVAL=#{scheduler_interval_secs}"
      - "PREDICT_DUMMY=#{predict_dummy}"
