version: "3"
services:
  admin_frontend:
    image: weatherpred_admin_frontend
    restart: unless-stopped
    ports:
      - "#{admin_port}:80"

  end_user:
    image: weatherpred_end_user_frontend
    restart: unless-stopped
    ports:
      - "#{end_user_port}:80"

  backend:
    image: weatherpred_backend
    restart: unless-stopped
    network_mode: "host"
    ports:
      - "#{backend_port}:7002"
    volumes:
      - "./db/:/app/db/"
      - "./files/:/app/files/"

  scheduler:
    image: weatherpred_scheduler
    restart: unless-stopped
    environment:
      - "BACKEND_URL=#{base_url}"
      - "SCHEDULER_INTERVAL=#{scheduler_interval_secs}"
      - "PREDICT_DUMMY=#{predict_dummy}"

  # tensorflow-serving-backend:
  #   image: tensorflow/serving:latest-gpu
  #   restart: unless-stopped
  #   ports:
  #     - 8500:8500
  #     - 8501:8501
  #   volumes:
  #     - ./backend/model:/models/cnnmodel 
  #   network_mode: "host"
  #   environment:
  #     - "MODEL_NAME=cnnmodel"